# Generated by Django 4.1.5 on 2023-01-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('average_salary', models.IntegerField()),
                ('vacancy_num', models.IntegerField()),
                ('selected_average_salary', models.IntegerField()),
                ('selected_vacancy_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'востребованность',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('average_salary', models.IntegerField()),
                ('percent_vacancy_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'география',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('skill_count', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'навыки',
            },
        ),
    ]
