# Generated by Django 4.1.5 on 2023-01-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('java_developer_analytic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('percent_vacancy_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'география-количество-вакансий',
            },
        ),
        migrations.CreateModel(
            name='GeographySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('average_salary', models.IntegerField()),
            ],
            options={
                'verbose_name': 'география-зарплаты',
            },
        ),
        migrations.DeleteModel(
            name='Geography',
        ),
    ]
